### ISSUE TITLE
Payment Gateway screen closes with "some error occured" message

### ISSUE THREAD

**Issue by subhamchatterjee** [Suraj-Tiwari/react-native-payumoney#63]
After I click on pay and the **Payumoney** function is called, the payment gateway screen opens, but after showing a loader with "**Getting payment details**" and trying to show the data, it fails after some time.

The logs that I am getting are as follows:

**With the dummy data you gave in the example:**
`{"amount": "10.0", "email": "xyz@gmail.com", "failedUrl": "https://www.payumoney.com/mobileapp/payumoney/failure.php", "firstName": "firstname", "hash": "461d4002c1432b3393cf2bfaae7acc4c50601c66568fb49a4a125e060c3bfc0e489290e7c902750d5db3fc8be2f180daf4d534d7b9bef46fa0158a4c8a057b61", "isDebug": true, "key": "QylhKRVd", "merchantId": "5960507", "phone": "9639999999", "productName": "product_info", "successUrl": "https://www.payumoney.com/mobileapp/payumoney/success.php", "txnId": "1594976828726", "udf1": "", "udf10": "", "udf2": "", "udf3": "", "udf4": "", "udf5": "", "udf6": "", "udf7": "", "udf8": "", "udf9": ""}`
 LOG  error: {"code": 0, "success": false}

**With my real-time data from the test server:**
`{"amount": 10, "email": "subham.b.chatterjee@gmail.com", "failedUrl": "https://testapi.subham.com/payment/gateway/payU/failure", "firstName": "Subham Chatterjee", "hash": "68e794632ab648e1f5c57dbe8cc7bc79571bc2462404eefe0c4a969c8cdf8a7b94bdaeba499d09933cf3a89848dd161db5ede12f46f16dddf5c1758888ff72a9", "isDebug": true, "key": "******", "merchantId": "*******", "phone": "**********", "productName": "Session purchase - id 6210dd8a16c4e83f08cc5743", "successUrl": "https://testapi.subham.com/payment/gateway/payU/success", "txnId": "rsUDKeG9LaTM3J10UayF", "udf1": "", "udf10": "", "udf2": "", "udf3": "", "udf4": "", "udf5": "", "udf6": "", "udf7": "", "udf8": "", "udf9": ""}
`
 LOG  error: {"code": 0, "success": false}

I have already verified the hash, with the Verify hash function that you provided, and the hash matches perfectly.
After sometime the gateway screen closes automatically, and a toast message shows "**some error occured**".

I am attaching a screenshot of the screen.
![Payu_error](https://user-images.githubusercontent.com/11857024/154849783-0d9fe618-0bf9-4519-8be5-e0be5ab1494f.jpeg)

**Comment by gurpreetpuri** [comment]
I have got same issue.
when call the payment function its return this response:- {"code": 0, "success": false}

**Comment by hirenpatel20283** [comment]
{"success":false,"code":0} getting same issue

**Comment by lalit-suthar-dev** [comment]
i am facing same issue {"success":false,"code":0} not getting it after many tries it still showing the same error again and again

**Comment by Suraj-Tiwari** [comment]
i've identified the issue and work is in progress, i'll create a release soon.

**Comment by sujanvaland** [comment]
Hello Suraj,

Any Update on this issue?

**Comment by Suraj-Tiwari** [comment]
I'm working on a new release, it's a full rewrite because of their new sdk and payumoney isn't helping at all their test cards doesn't work and payment gets failed, i wrote them email twice but they're ignorant, so i've to figure things out myself and work on assumptions, easiest could be if any of you've active account, i can make small real payments on them to test payment flow and send me amount back after work is done. 

Here is a capture of last conversation.

<img width="760" alt="Screenshot 2022-05-19 at 12 00 57 PM" src="https://user-images.githubusercontent.com/22210490/169225461-eebf4578-9e1f-4c6f-b8a7-d11a1e325709.png">

**Comment by mptechjolly** [comment]
Hello Suraj,

Any update on this issue? please let me know if you found any solution for below error.
payment function its return this response:- {"code": 0, "success": false}

**Comment by Suraj-Tiwari** [comment]
Unfortunately i did try with no success, payumoney released new sdk discontinuing currently used one by this package, i tried integrating but with no success because of improper test env credentials provided from their side, i can't test it, all i was able to do was invoke the sdk and start the payment flow till here
<img width="439" alt="Screenshot 2022-06-25 at 12 24 39 PM" src="https://user-images.githubusercontent.com/22210490/175762306-8d3f7bd9-1da2-4df7-893e-d187c10033e1.png">

after this i can't proceed as test cards fails with error "Bank failed to authenticate the customer due to 3D Secure Enrolment decline" i tried contacting them but they are just bunch of idiots, no support at all and their ans to solution was to do real payments. i don't earn from this project so i'm not willing to spent at all. i don't have any of my own merchant account where i can do test payments and get back that amount later. 
i'm only maintaining this project for community, if someone can provide me proper working merchant account where i can do real payments to test transactions and then once testing is done send me back that amount i spent after that, then i can proceed, otherwise this project is on halt.

**Comment by Suraj-Tiwari** [comment]
Looks like they've official sdk now [https://devguide.payu.in/mobile-sdk-react-native/getting-started-with-react-native-app/](https://devguide.payu.in/mobile-sdk-react-native/getting-started-with-react-native-app/)
